#!/usr/bin/env python3
"""
Embed audio data into daily words HTML file.
Usage: python embed-daily-words-audio.py <html_file> [output_file]
"""

import asyncio
import base64
import json
import re
import sys
from pathlib import Path

import edge_tts

# Voice configuration
VOICE = "en-NZ-MitchellNeural"
WORD_RATE = "-20%"      # Slower for words
SENTENCE_RATE = "-30%"  # Slower for sentences


async def generate_audio(text: str, rate: str = "0%") -> str:
    """Generate base64-encoded MP3 audio for given text."""
    communicate = edge_tts.Communicate(text, VOICE, rate=rate)
    audio_bytes = b""
    async for chunk in communicate.stream():
        if chunk["type"] == "audio":
            audio_bytes += chunk["data"]
    
    # Convert to base64 data URI
    b64 = base64.b64encode(audio_bytes).decode('utf-8')
    return f"data:audio/mp3;base64,{b64}"


def extract_speak_calls(html: str):
    """Extract all speakWord and speakSentence calls from onclick handlers."""
    results = []
    # Match: speakWord(this,'word') or speakSentence(this,'sentence')
    # Handle escaped quotes: \' inside the string
    pattern = r"(speakWord|speakSentence)\(this,'((?:[^'\\]|\\.)*?)'\)"
    for m in re.finditer(pattern, html):
        func = m.group(1)
        text = m.group(2).replace("\\'", "'")  # Unescape \' -> '
        rate = WORD_RATE if func == "speakWord" else SENTENCE_RATE
        results.append((m.start(), m.end(), func, text, rate))
    return results


async def main():
    from datetime import datetime
    from pathlib import Path
    
    if len(sys.argv) < 2:
        # Auto-detect today's file
        today = datetime.now().strftime('%Y-%m-%d')
        html_path = f"每日英语单词_{today}.html"
        if not Path(html_path).exists():
            # Try to find any daily words file
            files = list(Path('.').glob('每日英语单词_*.html'))
            if files:
                html_path = str(files[0])
            else:
                print("Error: No daily words HTML file found")
                sys.exit(1)
        output_path = html_path
        print(f"[*] Auto-detected file: {html_path}")
    else:
        html_path = sys.argv[1]
        output_path = sys.argv[2] if len(sys.argv) > 2 else html_path

    with open(html_path, "r", encoding="utf-8") as f:
        html = f.read()

    print(f"[*] Reading: {html_path}")

    # Extract all speak calls
    calls = extract_speak_calls(html)
    print(f"[*] Found {len(calls)} audio items to generate")

    # Generate all audio in parallel
    print(f"[*] Generating audio with voice: {VOICE} ...")
    audio_map = {}  # (start, end) -> data_uri
    tasks = []
    for start, end, func, text, rate in calls:
        tasks.append((start, end, text, generate_audio(text, rate)))

    for start, end, text, coro in tasks:
        data_uri = await coro
        audio_map[(start, end)] = data_uri

    print(f"[*] All {len(audio_map)} audio items generated. Embedding into HTML...")

    # Replace JS speak functions with base64 audio playback
    # Strategy: create an audio map object and replace each onclick handler
    # Build the audio map as JSON
    audio_data_js = "{\n"
    items = []
    for (start, end), data_uri in audio_map.items():
        # Use the text as key (escape for JS)
        key = f"{calls[[c[:2] for c in calls].index((start, end))][3]}"
        escaped_key = key.replace("\\", "\\\\").replace("'", "\\'")
        # Truncate base64 for readability in source, but keep full in actual
        items.append(f"  '{escaped_key}': '{data_uri}'")
    audio_data_js += ",\n".join(items)
    audio_data_js += "\n}"

    # Create the embedded audio player script
    embedded_script = f"""
<script>
// Embedded audio data generated by embed-daily-words-audio.py
const AUDIO_DATA = {audio_data_js};

function playEmbeddedAudio(text) {{
    const dataUri = AUDIO_DATA[text];
    if (!dataUri) {{
        console.error('Audio not found for:', text);
        return;
    }}
    
    // Create or reuse audio element
    let audio = document.getElementById('embedded-audio-player');
    if (!audio) {{
        audio = document.createElement('audio');
        audio.id = 'embedded-audio-player';
        document.body.appendChild(audio);
    }}
    
    audio.src = dataUri;
    audio.play().catch(e => console.error('Playback failed:', e));
}}

// Replace speakWord and speakSentence functions
function speakWord(el, text) {{
    playEmbeddedAudio(text);
}}

function speakSentence(el, text) {{
    playEmbeddedAudio(text);
}}
</script>
"""

    # Insert the script before </body>
    if "</body>" in html:
        html = html.replace("</body>", embedded_script + "\n</body>")
    else:
        # Append at the end if no </body>
        html += embedded_script

    # Write output
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"[*] Done! Output: {output_path}")
    print(f"[*] Audio embedded: {len(audio_map)} items")


if __name__ == "__main__":
    asyncio.run(main())
